// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmqzfqokgtykuryvjnsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcXpmcW9rZ3R5a3VyeXZqbnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NjU0MTAsImV4cCI6MjA3NzQ0MTQxMH0.yBWdsaqUff1GJo1iGmjBumx-01dwKKsGFF7t0gAqk6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});